version: "3.8"
services:
  database:
    image: mariadb:10.10
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3350:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
